package com.app.bean;
// Generated 2016-12-29 11:49:42 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysFuncInfo generated by hbm2java
 */
@Entity
@Table(name = "SYS_FUNC_INFO", catalog = "shopdata")
public class SysFuncInfo implements java.io.Serializable {

	private String id;
	private String name;
	private String url;
	private Integer level;
	private String target;
	private Integer seq;
	private String type;
	private String parentid;
	private String icon;
	private String desc;
	private Character status;
	private String sysId;
	private String subtxn;

	public SysFuncInfo() {
	}

	public SysFuncInfo(String id) {
		this.id = id;
	}

	public SysFuncInfo(String id, String name, String url, Integer level, String target, Integer seq, String type,
			String parentid, String icon, String desc, Character status, String sysId, String subtxn) {
		this.id = id;
		this.name = name;
		this.url = url;
		this.level = level;
		this.target = target;
		this.seq = seq;
		this.type = type;
		this.parentid = parentid;
		this.icon = icon;
		this.desc = desc;
		this.status = status;
		this.sysId = sysId;
		this.subtxn = subtxn;
	}

	@Id

	@Column(name = "id_", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name_", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url_", length = 225)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "level_")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "target_", length = 10)
	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	@Column(name = "seq_")
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Column(name = "type_", length = 2)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "parentid_", length = 32)
	public String getParentid() {
		return this.parentid;
	}

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	@Column(name = "icon_", length = 10)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "desc_", length = 200)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Column(name = "status_", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "sys_id", length = 4)
	public String getSysId() {
		return this.sysId;
	}

	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	@Column(name = "subtxn", length = 40)
	public String getSubtxn() {
		return this.subtxn;
	}

	public void setSubtxn(String subtxn) {
		this.subtxn = subtxn;
	}

}
