package com.app.bean;

// Generated 2016-8-17 22:57:52 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblAddressInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_address_info", catalog = "shopdata")
public class TblAddressInfo implements java.io.Serializable {

	private String addrId;
	private String userId;
	private String addrNm;
	private String provice;
	private String city;
	private String zone;
	private String address;
	private String consignee;
	private String mobile;
	private String tel;
	private String isMain;

	public TblAddressInfo() {
	}

	public TblAddressInfo(String addrId) {
		this.addrId = addrId;
	}

	public TblAddressInfo(String addrId, String userId, String addrNm,
			String provice, String city, String zone, String address,
			String consignee, String mobile, String tel, String isMain) {
		this.addrId = addrId;
		this.userId = userId;
		this.addrNm = addrNm;
		this.provice = provice;
		this.city = city;
		this.zone = zone;
		this.address = address;
		this.consignee = consignee;
		this.mobile = mobile;
		this.tel = tel;
		this.isMain = isMain;
	}

	@Id
	@Column(name = "addr_id", unique = true, nullable = false, length = 32)
	public String getAddrId() {
		return this.addrId;
	}

	public void setAddrId(String addrId) {
		this.addrId = addrId;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "addr_nm", length = 50)
	public String getAddrNm() {
		return this.addrNm;
	}

	public void setAddrNm(String addrNm) {
		this.addrNm = addrNm;
	}

	@Column(name = "provice", length = 20)
	public String getProvice() {
		return this.provice;
	}

	public void setProvice(String provice) {
		this.provice = provice;
	}

	@Column(name = "city", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "zone", length = 20)
	public String getZone() {
		return this.zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "consignee", length = 50)
	public String getConsignee() {
		return this.consignee;
	}

	public void setConsignee(String consignee) {
		this.consignee = consignee;
	}

	@Column(name = "mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "tel", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "isMain", length = 1)
	public String getIsMain() {
		return this.isMain;
	}

	public void setIsMain(String isMain) {
		this.isMain = isMain;
	}

}
