package com.app.bean;
// Generated 2016-12-14 21:15:15 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblBannerInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_banner_info", catalog = "shopdata")
public class TblBannerInfo implements java.io.Serializable {

	private String bannerId;
	private String type;
	private String title;
	private String resId;
	private String background;
	private String url;
	private String status;
	private String instDt;
	private String instOper;
	private String modiDt;
	private String modiOper;
	private String rev;

	public TblBannerInfo() {
	}

	public TblBannerInfo(String bannerId) {
		this.bannerId = bannerId;
	}

	public TblBannerInfo(String bannerId, String type, String title, String resId, String background, String url,
			String status, String instDt, String instOper, String modiDt, String modiOper, String rev) {
		this.bannerId = bannerId;
		this.type = type;
		this.title = title;
		this.resId = resId;
		this.background = background;
		this.url = url;
		this.status = status;
		this.instDt = instDt;
		this.instOper = instOper;
		this.modiDt = modiDt;
		this.modiOper = modiOper;
		this.rev = rev;
	}

	@Id

	@Column(name = "banner_id", unique = true, nullable = false, length = 32)
	public String getBannerId() {
		return this.bannerId;
	}

	public void setBannerId(String bannerId) {
		this.bannerId = bannerId;
	}

	@Column(name = "type", length = 4)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "title", length = 60)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "res_id", length = 32)
	public String getResId() {
		return this.resId;
	}

	public void setResId(String resId) {
		this.resId = resId;
	}

	@Column(name = "background", length = 20)
	public String getBackground() {
		return this.background;
	}

	public void setBackground(String background) {
		this.background = background;
	}

	@Column(name = "url", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "inst_dt", length = 14)
	public String getInstDt() {
		return this.instDt;
	}

	public void setInstDt(String instDt) {
		this.instDt = instDt;
	}

	@Column(name = "inst_oper", length = 20)
	public String getInstOper() {
		return this.instOper;
	}

	public void setInstOper(String instOper) {
		this.instOper = instOper;
	}

	@Column(name = "modi_dt", length = 14)
	public String getModiDt() {
		return this.modiDt;
	}

	public void setModiDt(String modiDt) {
		this.modiDt = modiDt;
	}

	@Column(name = "modi_oper", length = 20)
	public String getModiOper() {
		return this.modiOper;
	}

	public void setModiOper(String modiOper) {
		this.modiOper = modiOper;
	}

	@Column(name = "rev", length = 100)
	public String getRev() {
		return this.rev;
	}

	public void setRev(String rev) {
		this.rev = rev;
	}

}
