package com.app.bean;
// Generated 2017-3-31 11:47:49 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblBuyCarInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_buy_car_info", catalog = "shopdata")
public class TblBuyCarInfo implements java.io.Serializable {

	private String seqId;
	private String instDt;
	private String userId;
	private String shopId;
	private String shopNm;
	private String goodsId;
	private String goodsNm;
	private String typeId;
	private String typeNm;
	private Integer buyNum;
	private String rev;

	public TblBuyCarInfo() {
	}

	public TblBuyCarInfo(String seqId) {
		this.seqId = seqId;
	}

	public TblBuyCarInfo(String seqId, String instDt, String userId, String shopId, String shopNm, String goodsId,
			String goodsNm, String typeId, String typeNm, Integer buyNum, String rev) {
		this.seqId = seqId;
		this.instDt = instDt;
		this.userId = userId;
		this.shopId = shopId;
		this.shopNm = shopNm;
		this.goodsId = goodsId;
		this.goodsNm = goodsNm;
		this.typeId = typeId;
		this.typeNm = typeNm;
		this.buyNum = buyNum;
		this.rev = rev;
	}

	@Id

	@Column(name = "seq_id", unique = true, nullable = false, length = 32)
	public String getSeqId() {
		return this.seqId;
	}

	public void setSeqId(String seqId) {
		this.seqId = seqId;
	}

	@Column(name = "inst_dt", length = 14)
	public String getInstDt() {
		return this.instDt;
	}

	public void setInstDt(String instDt) {
		this.instDt = instDt;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "shop_id", length = 32)
	public String getShopId() {
		return this.shopId;
	}

	public void setShopId(String shopId) {
		this.shopId = shopId;
	}

	@Column(name = "shop_nm", length = 100)
	public String getShopNm() {
		return this.shopNm;
	}

	public void setShopNm(String shopNm) {
		this.shopNm = shopNm;
	}

	@Column(name = "goods_id", length = 32)
	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	@Column(name = "goods_nm", length = 100)
	public String getGoodsNm() {
		return this.goodsNm;
	}

	public void setGoodsNm(String goodsNm) {
		this.goodsNm = goodsNm;
	}

	@Column(name = "type_id", length = 32)
	public String getTypeId() {
		return this.typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	@Column(name = "type_nm", length = 100)
	public String getTypeNm() {
		return this.typeNm;
	}

	public void setTypeNm(String typeNm) {
		this.typeNm = typeNm;
	}

	@Column(name = "buy_num")
	public Integer getBuyNum() {
		return this.buyNum;
	}

	public void setBuyNum(Integer buyNum) {
		this.buyNum = buyNum;
	}

	@Column(name = "rev", length = 45)
	public String getRev() {
		return this.rev;
	}

	public void setRev(String rev) {
		this.rev = rev;
	}

}
