package com.app.bean;

// Generated 2016-7-20 23:30:12 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblBindInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_bind_info", catalog = "shopdata")
public class TblBindInfo implements java.io.Serializable {

	private String bindNo;
	private String keyA;
	private String keyB;
	private String bindSta;
	private String mode;
	private String content;
	private String bindDt;

	public TblBindInfo() {
	}

	public TblBindInfo(String bindNo) {
		this.bindNo = bindNo;
	}

	public TblBindInfo(String bindNo, String keyA, String keyB, String bindSta,
			String mode, String content, String bindDt) {
		this.bindNo = bindNo;
		this.keyA = keyA;
		this.keyB = keyB;
		this.bindSta = bindSta;
		this.mode = mode;
		this.content = content;
		this.bindDt = bindDt;
	}

	@Id
	@Column(name = "bindNo", unique = true, nullable = false, length = 32)
	public String getBindNo() {
		return this.bindNo;
	}

	public void setBindNo(String bindNo) {
		this.bindNo = bindNo;
	}

	@Column(name = "keyA", length = 32)
	public String getKeyA() {
		return this.keyA;
	}

	public void setKeyA(String keyA) {
		this.keyA = keyA;
	}

	@Column(name = "keyB", length = 32)
	public String getKeyB() {
		return this.keyB;
	}

	public void setKeyB(String keyB) {
		this.keyB = keyB;
	}

	@Column(name = "bindSta", length = 1)
	public String getBindSta() {
		return this.bindSta;
	}

	public void setBindSta(String bindSta) {
		this.bindSta = bindSta;
	}

	@Column(name = "mode", length = 2)
	public String getMode() {
		return this.mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	@Column(name = "content", length = 100)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "bindDt", length = 14)
	public String getBindDt() {
		return this.bindDt;
	}

	public void setBindDt(String bindDt) {
		this.bindDt = bindDt;
	}

}
