package com.app.bean;
// Generated 2016-10-30 22:21:24 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblCustomerInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_customer_info", catalog = "shopdata")
public class TblCustomerInfo implements java.io.Serializable {

	private String custId;
	private String custSta;
	private String grade;
	private String rzFlag;
	private String custNm;
	private String certType;
	private String certNo;
	private String telPhone;
	private String email;
	private String niciNm;
	private String gender;
	private String homePhone;
	private String officePhone;
	private String addr;
	private String regDt;
	private String modiDt;

	public TblCustomerInfo() {
	}

	public TblCustomerInfo(String custId) {
		this.custId = custId;
	}

	public TblCustomerInfo(String custId, String custSta, String grade, String rzFlag, String custNm, String certType,
			String certNo, String telPhone, String email, String niciNm, String gender, String homePhone,
			String officePhone, String addr, String regDt, String modiDt) {
		this.custId = custId;
		this.custSta = custSta;
		this.grade = grade;
		this.rzFlag = rzFlag;
		this.custNm = custNm;
		this.certType = certType;
		this.certNo = certNo;
		this.telPhone = telPhone;
		this.email = email;
		this.niciNm = niciNm;
		this.gender = gender;
		this.homePhone = homePhone;
		this.officePhone = officePhone;
		this.addr = addr;
		this.regDt = regDt;
		this.modiDt = modiDt;
	}

	@Id

	@Column(name = "custId", unique = true, nullable = false, length = 32)
	public String getCustId() {
		return this.custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	@Column(name = "custSta", length = 1)
	public String getCustSta() {
		return this.custSta;
	}

	public void setCustSta(String custSta) {
		this.custSta = custSta;
	}

	@Column(name = "grade", length = 2)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "rzFlag", length = 10)
	public String getRzFlag() {
		return this.rzFlag;
	}

	public void setRzFlag(String rzFlag) {
		this.rzFlag = rzFlag;
	}

	@Column(name = "custNm", length = 50)
	public String getCustNm() {
		return this.custNm;
	}

	public void setCustNm(String custNm) {
		this.custNm = custNm;
	}

	@Column(name = "certType", length = 2)
	public String getCertType() {
		return this.certType;
	}

	public void setCertType(String certType) {
		this.certType = certType;
	}

	@Column(name = "certNo", length = 20)
	public String getCertNo() {
		return this.certNo;
	}

	public void setCertNo(String certNo) {
		this.certNo = certNo;
	}

	@Column(name = "telPhone", length = 20)
	public String getTelPhone() {
		return this.telPhone;
	}

	public void setTelPhone(String telPhone) {
		this.telPhone = telPhone;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "niciNm", length = 50)
	public String getNiciNm() {
		return this.niciNm;
	}

	public void setNiciNm(String niciNm) {
		this.niciNm = niciNm;
	}

	@Column(name = "gender", length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "homePhone", length = 15)
	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	@Column(name = "officePhone", length = 15)
	public String getOfficePhone() {
		return this.officePhone;
	}

	public void setOfficePhone(String officePhone) {
		this.officePhone = officePhone;
	}

	@Column(name = "addr", length = 100)
	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	@Column(name = "regDt", length = 14)
	public String getRegDt() {
		return this.regDt;
	}

	public void setRegDt(String regDt) {
		this.regDt = regDt;
	}

	@Column(name = "modiDt", length = 14)
	public String getModiDt() {
		return this.modiDt;
	}

	public void setModiDt(String modiDt) {
		this.modiDt = modiDt;
	}

}
