package com.app.bean;

// Generated 2016-6-4 23:14:52 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblGoodsTypeInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_goods_type_info", catalog = "shopdata")
public class TblGoodsTypeInfo implements java.io.Serializable {

	private String typeId;
	private String goodsId;
	private String typeNm;
	private String kind;
	private String price;
	private Integer store;
	private String resid;
	private String weight;
	private String bulk;
	private String other;
	private String other1;
	private String other2;
	private String other3;

	public TblGoodsTypeInfo() {
	}

	public TblGoodsTypeInfo(String typeId) {
		this.typeId = typeId;
	}

	public TblGoodsTypeInfo(String typeId, String goodsId, String typeNm,
			String kind, String price, Integer store, String resid,
			String weight, String bulk, String other, String other1,
			String other2, String other3) {
		this.typeId = typeId;
		this.goodsId = goodsId;
		this.typeNm = typeNm;
		this.kind = kind;
		this.price = price;
		this.store = store;
		this.resid = resid;
		this.weight = weight;
		this.bulk = bulk;
		this.other = other;
		this.other1 = other1;
		this.other2 = other2;
		this.other3 = other3;
	}

	@Id
	@Column(name = "type_id", unique = true, nullable = false, length = 32)
	public String getTypeId() {
		return this.typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	@Column(name = "goods_id", length = 32)
	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	@Column(name = "type_nm", length = 30)
	public String getTypeNm() {
		return this.typeNm;
	}

	public void setTypeNm(String typeNm) {
		this.typeNm = typeNm;
	}

	@Column(name = "kind", length = 1)
	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	@Column(name = "price", length = 12)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "store")
	public Integer getStore() {
		return this.store;
	}

	public void setStore(Integer store) {
		this.store = store;
	}

	@Column(name = "resid", length = 32)
	public String getResid() {
		return this.resid;
	}

	public void setResid(String resid) {
		this.resid = resid;
	}

	@Column(name = "weight", length = 20)
	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	@Column(name = "bulk", length = 20)
	public String getBulk() {
		return this.bulk;
	}

	public void setBulk(String bulk) {
		this.bulk = bulk;
	}

	@Column(name = "other", length = 20)
	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	@Column(name = "other1", length = 20)
	public String getOther1() {
		return this.other1;
	}

	public void setOther1(String other1) {
		this.other1 = other1;
	}

	@Column(name = "other2", length = 20)
	public String getOther2() {
		return this.other2;
	}

	public void setOther2(String other2) {
		this.other2 = other2;
	}

	@Column(name = "other3", length = 20)
	public String getOther3() {
		return this.other3;
	}

	public void setOther3(String other3) {
		this.other3 = other3;
	}

}
