package com.app.bean;
// Generated 2017-3-24 20:19:53 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblInterestShopInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_interest_shop_info", catalog = "shopdata")
public class TblInterestShopInfo implements java.io.Serializable {

	private String inteId;
	private String userId;
	private String actType;
	private String shopId;
	private String channel;
	private String status;
	private String instDt;
	private String instOper;
	private String updateDt;
	private String updateOper;
	private String rev;

	public TblInterestShopInfo() {
	}

	public TblInterestShopInfo(String inteId) {
		this.inteId = inteId;
	}

	public TblInterestShopInfo(String inteId, String userId, String actType, String shopId, String channel,
			String status, String instDt, String instOper, String updateDt, String updateOper, String rev) {
		this.inteId = inteId;
		this.userId = userId;
		this.actType = actType;
		this.shopId = shopId;
		this.channel = channel;
		this.status = status;
		this.instDt = instDt;
		this.instOper = instOper;
		this.updateDt = updateDt;
		this.updateOper = updateOper;
		this.rev = rev;
	}

	@Id

	@Column(name = "inte_id", unique = true, nullable = false, length = 32)
	public String getInteId() {
		return this.inteId;
	}

	public void setInteId(String inteId) {
		this.inteId = inteId;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "act_type", length = 4)
	public String getActType() {
		return this.actType;
	}

	public void setActType(String actType) {
		this.actType = actType;
	}

	@Column(name = "shop_id", length = 32)
	public String getShopId() {
		return this.shopId;
	}

	public void setShopId(String shopId) {
		this.shopId = shopId;
	}

	@Column(name = "channel", length = 1)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "inst_dt", length = 14)
	public String getInstDt() {
		return this.instDt;
	}

	public void setInstDt(String instDt) {
		this.instDt = instDt;
	}

	@Column(name = "inst_oper", length = 20)
	public String getInstOper() {
		return this.instOper;
	}

	public void setInstOper(String instOper) {
		this.instOper = instOper;
	}

	@Column(name = "update_dt", length = 14)
	public String getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(String updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_oper", length = 20)
	public String getUpdateOper() {
		return this.updateOper;
	}

	public void setUpdateOper(String updateOper) {
		this.updateOper = updateOper;
	}

	@Column(name = "rev", length = 100)
	public String getRev() {
		return this.rev;
	}

	public void setRev(String rev) {
		this.rev = rev;
	}

}
