package com.app.bean;
// Generated 2016-12-18 15:04:11 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblNavClassifyChildInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_nav_classify_child_info", catalog = "shopdata")
public class TblNavClassifyChildInfo implements java.io.Serializable {

	private String childid;
	private String classify;
	private String ctype;
	private String cname;
	private String url;
	private String status;
	private String instDt;
	private String instOper;
	private String modiDt;
	private String modiOper;

	public TblNavClassifyChildInfo() {
	}

	public TblNavClassifyChildInfo(String childid) {
		this.childid = childid;
	}

	public TblNavClassifyChildInfo(String childid, String classify, String ctype, String cname, String url,
			String status, String instDt, String instOper, String modiDt, String modiOper) {
		this.childid = childid;
		this.classify = classify;
		this.ctype = ctype;
		this.cname = cname;
		this.url = url;
		this.status = status;
		this.instDt = instDt;
		this.instOper = instOper;
		this.modiDt = modiDt;
		this.modiOper = modiOper;
	}

	@Id

	@Column(name = "childid", unique = true, nullable = false, length = 32)
	public String getChildid() {
		return this.childid;
	}

	public void setChildid(String childid) {
		this.childid = childid;
	}

	@Column(name = "classify", length = 32)
	public String getClassify() {
		return this.classify;
	}

	public void setClassify(String classify) {
		this.classify = classify;
	}

	@Column(name = "ctype", length = 4)
	public String getCtype() {
		return this.ctype;
	}

	public void setCtype(String ctype) {
		this.ctype = ctype;
	}

	@Column(name = "cname", length = 100)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Column(name = "url", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "inst_dt", length = 14)
	public String getInstDt() {
		return this.instDt;
	}

	public void setInstDt(String instDt) {
		this.instDt = instDt;
	}

	@Column(name = "inst_oper", length = 20)
	public String getInstOper() {
		return this.instOper;
	}

	public void setInstOper(String instOper) {
		this.instOper = instOper;
	}

	@Column(name = "modi_dt", length = 14)
	public String getModiDt() {
		return this.modiDt;
	}

	public void setModiDt(String modiDt) {
		this.modiDt = modiDt;
	}

	@Column(name = "modi_oper", length = 20)
	public String getModiOper() {
		return this.modiOper;
	}

	public void setModiOper(String modiOper) {
		this.modiOper = modiOper;
	}

}
