package com.app.bean;
// Generated 2016-12-18 14:10:30 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblNavClassifyInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_nav_classify_info", catalog = "shopdata")
public class TblNavClassifyInfo implements java.io.Serializable {

	private String classify;
	private String ctype;
	private String cname;
	private String clevel;
	private Integer cflag;
	private Integer cseq;
	private String pclassify;
	private String icon;
	private String url;
	private String status;
	private String instDt;
	private String instOper;
	private String modiDt;
	private String modiOper;

	public TblNavClassifyInfo() {
	}

	public TblNavClassifyInfo(String classify) {
		this.classify = classify;
	}

	public TblNavClassifyInfo(String classify, String ctype, String cname, String clevel, Integer cflag, Integer cseq,
			String pclassify, String icon, String url, String status, String instDt, String instOper, String modiDt,
			String modiOper) {
		this.classify = classify;
		this.ctype = ctype;
		this.cname = cname;
		this.clevel = clevel;
		this.cflag = cflag;
		this.cseq = cseq;
		this.pclassify = pclassify;
		this.icon = icon;
		this.url = url;
		this.status = status;
		this.instDt = instDt;
		this.instOper = instOper;
		this.modiDt = modiDt;
		this.modiOper = modiOper;
	}

	@Id

	@Column(name = "classify", unique = true, nullable = false, length = 32)
	public String getClassify() {
		return this.classify;
	}

	public void setClassify(String classify) {
		this.classify = classify;
	}

	@Column(name = "ctype", length = 4)
	public String getCtype() {
		return this.ctype;
	}

	public void setCtype(String ctype) {
		this.ctype = ctype;
	}

	@Column(name = "cname", length = 100)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Column(name = "clevel", length = 1)
	public String getClevel() {
		return this.clevel;
	}

	public void setClevel(String clevel) {
		this.clevel = clevel;
	}

	@Column(name = "cflag")
	public Integer getCflag() {
		return this.cflag;
	}

	public void setCflag(Integer cflag) {
		this.cflag = cflag;
	}

	@Column(name = "cseq")
	public Integer getCseq() {
		return this.cseq;
	}

	public void setCseq(Integer cseq) {
		this.cseq = cseq;
	}

	@Column(name = "pclassify", length = 32)
	public String getPclassify() {
		return this.pclassify;
	}

	public void setPclassify(String pclassify) {
		this.pclassify = pclassify;
	}

	@Column(name = "icon", length = 200)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "url", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "inst_dt", length = 14)
	public String getInstDt() {
		return this.instDt;
	}

	public void setInstDt(String instDt) {
		this.instDt = instDt;
	}

	@Column(name = "inst_oper", length = 20)
	public String getInstOper() {
		return this.instOper;
	}

	public void setInstOper(String instOper) {
		this.instOper = instOper;
	}

	@Column(name = "modi_dt", length = 14)
	public String getModiDt() {
		return this.modiDt;
	}

	public void setModiDt(String modiDt) {
		this.modiDt = modiDt;
	}

	@Column(name = "modi_oper", length = 20)
	public String getModiOper() {
		return this.modiOper;
	}

	public void setModiOper(String modiOper) {
		this.modiOper = modiOper;
	}

}
