package com.app.bean;
// Generated 2016-11-10 20:33:56 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblNoticeInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_notice_info", catalog = "shopdata")
public class TblNoticeInfo implements java.io.Serializable {

	private String noteId;
	private String noteNm;
	private String title;
	private String content;
	private String noteType;
	private String hot;
	private String noteSta;
	private String instDt;
	private String instOper;
	private String modiDt;
	private String modiOper;

	public TblNoticeInfo() {
	}

	public TblNoticeInfo(String noteId) {
		this.noteId = noteId;
	}

	public TblNoticeInfo(String noteId, String noteNm, String title, String content, String noteType, String hot,
			String noteSta, String instDt, String instOper, String modiDt, String modiOper) {
		this.noteId = noteId;
		this.noteNm = noteNm;
		this.title = title;
		this.content = content;
		this.noteType = noteType;
		this.hot = hot;
		this.noteSta = noteSta;
		this.instDt = instDt;
		this.instOper = instOper;
		this.modiDt = modiDt;
		this.modiOper = modiOper;
	}

	@Id

	@Column(name = "note_id", unique = true, nullable = false, length = 32)
	public String getNoteId() {
		return this.noteId;
	}

	public void setNoteId(String noteId) {
		this.noteId = noteId;
	}

	@Column(name = "note_nm", length = 100)
	public String getNoteNm() {
		return this.noteNm;
	}

	public void setNoteNm(String noteNm) {
		this.noteNm = noteNm;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 4096)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "note_type", length = 2)
	public String getNoteType() {
		return this.noteType;
	}

	public void setNoteType(String noteType) {
		this.noteType = noteType;
	}

	@Column(name = "hot", length = 1)
	public String getHot() {
		return this.hot;
	}

	public void setHot(String hot) {
		this.hot = hot;
	}

	@Column(name = "note_sta", length = 1)
	public String getNoteSta() {
		return this.noteSta;
	}

	public void setNoteSta(String noteSta) {
		this.noteSta = noteSta;
	}

	@Column(name = "inst_dt", length = 14)
	public String getInstDt() {
		return this.instDt;
	}

	public void setInstDt(String instDt) {
		this.instDt = instDt;
	}

	@Column(name = "inst_oper", length = 20)
	public String getInstOper() {
		return this.instOper;
	}

	public void setInstOper(String instOper) {
		this.instOper = instOper;
	}

	@Column(name = "modi_dt", length = 14)
	public String getModiDt() {
		return this.modiDt;
	}

	public void setModiDt(String modiDt) {
		this.modiDt = modiDt;
	}

	@Column(name = "modi_oper", length = 20)
	public String getModiOper() {
		return this.modiOper;
	}

	public void setModiOper(String modiOper) {
		this.modiOper = modiOper;
	}

}
