package com.app.bean;
// Generated 2017-4-18 22:49:58 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblOrderInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_order_info", catalog = "shopdata")
public class TblOrderInfo implements java.io.Serializable {

	private String orderId;
	private String sendChannle;
	private String applyDt;
	private String payDt;
	private String outDt;
	private String confirmDt;
	private String closeDt;
	private String autoDt;
	private String userId;
	private String userNm;
	private String shopId;
	private String shopNm;
	private String totalNum;
	private String goodsAmt;
	private String yfAmt;
	private String totalAmt;
	private String buyerMsg;
	private String salerMsg;
	private String payAmt;
	private String addrs;
	private String person;
	private String mobile;
	private String ordSta;
	private String paySta;
	private String paySeq;
	private String payChannle;
	private String express;
	private String expressNo;
	private String instDt;
	private String modiDt;

	public TblOrderInfo() {
	}

	public TblOrderInfo(String orderId) {
		this.orderId = orderId;
	}

	public TblOrderInfo(String orderId, String sendChannle, String applyDt, String payDt, String outDt,
			String confirmDt, String closeDt, String autoDt, String userId, String userNm, String shopId, String shopNm,
			String totalNum, String goodsAmt, String yfAmt, String totalAmt, String buyerMsg, String salerMsg,
			String payAmt, String addrs, String person, String mobile, String ordSta, String paySta, String paySeq,
			String payChannle, String express, String expressNo, String instDt, String modiDt) {
		this.orderId = orderId;
		this.sendChannle = sendChannle;
		this.applyDt = applyDt;
		this.payDt = payDt;
		this.outDt = outDt;
		this.confirmDt = confirmDt;
		this.closeDt = closeDt;
		this.autoDt = autoDt;
		this.userId = userId;
		this.userNm = userNm;
		this.shopId = shopId;
		this.shopNm = shopNm;
		this.totalNum = totalNum;
		this.goodsAmt = goodsAmt;
		this.yfAmt = yfAmt;
		this.totalAmt = totalAmt;
		this.buyerMsg = buyerMsg;
		this.salerMsg = salerMsg;
		this.payAmt = payAmt;
		this.addrs = addrs;
		this.person = person;
		this.mobile = mobile;
		this.ordSta = ordSta;
		this.paySta = paySta;
		this.paySeq = paySeq;
		this.payChannle = payChannle;
		this.express = express;
		this.expressNo = expressNo;
		this.instDt = instDt;
		this.modiDt = modiDt;
	}

	@Id

	@Column(name = "order_id", unique = true, nullable = false, length = 32)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "send_channle", length = 1)
	public String getSendChannle() {
		return this.sendChannle;
	}

	public void setSendChannle(String sendChannle) {
		this.sendChannle = sendChannle;
	}

	@Column(name = "apply_dt", length = 14)
	public String getApplyDt() {
		return this.applyDt;
	}

	public void setApplyDt(String applyDt) {
		this.applyDt = applyDt;
	}

	@Column(name = "pay_dt", length = 14)
	public String getPayDt() {
		return this.payDt;
	}

	public void setPayDt(String payDt) {
		this.payDt = payDt;
	}

	@Column(name = "out_dt", length = 14)
	public String getOutDt() {
		return this.outDt;
	}

	public void setOutDt(String outDt) {
		this.outDt = outDt;
	}

	@Column(name = "confirm_dt", length = 14)
	public String getConfirmDt() {
		return this.confirmDt;
	}

	public void setConfirmDt(String confirmDt) {
		this.confirmDt = confirmDt;
	}

	@Column(name = "close_dt", length = 14)
	public String getCloseDt() {
		return this.closeDt;
	}

	public void setCloseDt(String closeDt) {
		this.closeDt = closeDt;
	}

	@Column(name = "auto_dt", length = 14)
	public String getAutoDt() {
		return this.autoDt;
	}

	public void setAutoDt(String autoDt) {
		this.autoDt = autoDt;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "user_nm", length = 100)
	public String getUserNm() {
		return this.userNm;
	}

	public void setUserNm(String userNm) {
		this.userNm = userNm;
	}

	@Column(name = "shop_id", length = 32)
	public String getShopId() {
		return this.shopId;
	}

	public void setShopId(String shopId) {
		this.shopId = shopId;
	}

	@Column(name = "shop_nm", length = 100)
	public String getShopNm() {
		return this.shopNm;
	}

	public void setShopNm(String shopNm) {
		this.shopNm = shopNm;
	}

	@Column(name = "total_num", length = 8)
	public String getTotalNum() {
		return this.totalNum;
	}

	public void setTotalNum(String totalNum) {
		this.totalNum = totalNum;
	}

	@Column(name = "goods_amt", length = 12)
	public String getGoodsAmt() {
		return this.goodsAmt;
	}

	public void setGoodsAmt(String goodsAmt) {
		this.goodsAmt = goodsAmt;
	}

	@Column(name = "yf_amt", length = 12)
	public String getYfAmt() {
		return this.yfAmt;
	}

	public void setYfAmt(String yfAmt) {
		this.yfAmt = yfAmt;
	}

	@Column(name = "total_amt", length = 12)
	public String getTotalAmt() {
		return this.totalAmt;
	}

	public void setTotalAmt(String totalAmt) {
		this.totalAmt = totalAmt;
	}

	@Column(name = "buyer_msg", length = 200)
	public String getBuyerMsg() {
		return this.buyerMsg;
	}

	public void setBuyerMsg(String buyerMsg) {
		this.buyerMsg = buyerMsg;
	}

	@Column(name = "saler_msg", length = 200)
	public String getSalerMsg() {
		return this.salerMsg;
	}

	public void setSalerMsg(String salerMsg) {
		this.salerMsg = salerMsg;
	}

	@Column(name = "pay_amt", length = 12)
	public String getPayAmt() {
		return this.payAmt;
	}

	public void setPayAmt(String payAmt) {
		this.payAmt = payAmt;
	}

	@Column(name = "addrs", length = 150)
	public String getAddrs() {
		return this.addrs;
	}

	public void setAddrs(String addrs) {
		this.addrs = addrs;
	}

	@Column(name = "person", length = 30)
	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	@Column(name = "mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "ord_sta", length = 2)
	public String getOrdSta() {
		return this.ordSta;
	}

	public void setOrdSta(String ordSta) {
		this.ordSta = ordSta;
	}

	@Column(name = "pay_sta", length = 2)
	public String getPaySta() {
		return this.paySta;
	}

	public void setPaySta(String paySta) {
		this.paySta = paySta;
	}

	@Column(name = "pay_seq", length = 32)
	public String getPaySeq() {
		return this.paySeq;
	}

	public void setPaySeq(String paySeq) {
		this.paySeq = paySeq;
	}

	@Column(name = "pay_channle", length = 2)
	public String getPayChannle() {
		return this.payChannle;
	}

	public void setPayChannle(String payChannle) {
		this.payChannle = payChannle;
	}

	@Column(name = "express", length = 50)
	public String getExpress() {
		return this.express;
	}

	public void setExpress(String express) {
		this.express = express;
	}

	@Column(name = "express_no", length = 30)
	public String getExpressNo() {
		return this.expressNo;
	}

	public void setExpressNo(String expressNo) {
		this.expressNo = expressNo;
	}

	@Column(name = "inst_dt", length = 14)
	public String getInstDt() {
		return this.instDt;
	}

	public void setInstDt(String instDt) {
		this.instDt = instDt;
	}

	@Column(name = "modi_dt", length = 14)
	public String getModiDt() {
		return this.modiDt;
	}

	public void setModiDt(String modiDt) {
		this.modiDt = modiDt;
	}

}
