package com.app.bean;
// Generated 2017-3-17 10:30:17 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblOauth2UserInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_oauth2_user_info", catalog = "shopdata")
public class TblOauth2UserInfo implements java.io.Serializable {

	private String oauth2Id;
	private String userId;
	private String platform;
	private String channel;
	private String openid;
	private String accessToken;
	private Integer expires;
	private String headimgurl;

	public TblOauth2UserInfo() {
	}

	public TblOauth2UserInfo(String oauth2Id) {
		this.oauth2Id = oauth2Id;
	}

	public TblOauth2UserInfo(String oauth2Id, String userId, String platform, String channel, String openid,
			String accessToken, Integer expires, String headimgurl) {
		this.oauth2Id = oauth2Id;
		this.userId = userId;
		this.platform = platform;
		this.channel = channel;
		this.openid = openid;
		this.accessToken = accessToken;
		this.expires = expires;
		this.headimgurl = headimgurl;
	}

	@Id

	@Column(name = "oauth2_id", unique = true, nullable = false, length = 32)
	public String getOauth2Id() {
		return this.oauth2Id;
	}

	public void setOauth2Id(String oauth2Id) {
		this.oauth2Id = oauth2Id;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "platform", length = 1)
	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	@Column(name = "channel", length = 1)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Column(name = "openid", length = 45)
	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	@Column(name = "access_token", length = 200)
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Column(name = "expires")
	public Integer getExpires() {
		return this.expires;
	}

	public void setExpires(Integer expires) {
		this.expires = expires;
	}

	@Column(name = "headimgurl", length = 200)
	public String getHeadimgurl() {
		return this.headimgurl;
	}

	public void setHeadimgurl(String headimgurl) {
		this.headimgurl = headimgurl;
	}

}
