package com.app.bean;
// Generated 2017-4-17 22:54:07 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblPayDtl generated by hbm2java
 */
@Entity
@Table(name = "tbl_pay_dtl", catalog = "shopdata")
public class TblPayDtl implements java.io.Serializable {

	private String paySeq;
	private String instDt;
	private String payChannle;
	private String orderId;
	private String totalAmt;
	private String timeStart;
	private String timeExpire;
	private String paySta;
	private String rev;
	private String returnCode;
	private String returnMsg;
	private String resultCode;
	private String errCode;
	private String errCodeDes;
	private String tradeType;
	private String prepayId;
	private String codeUrl;
	private String bankType;
	private String transactionId;
	private String payTimeEnd;
	private String sendChannle;
	private String orderDesc;

	public TblPayDtl() {
	}

	public TblPayDtl(String paySeq) {
		this.paySeq = paySeq;
	}

	public TblPayDtl(String paySeq, String instDt, String payChannle, String orderId, String totalAmt, String timeStart,
			String timeExpire, String paySta, String rev, String returnCode, String returnMsg, String resultCode,
			String errCode, String errCodeDes, String tradeType, String prepayId, String codeUrl, String bankType,
			String transactionId, String payTimeEnd, String sendChannle, String orderDesc) {
		this.paySeq = paySeq;
		this.instDt = instDt;
		this.payChannle = payChannle;
		this.orderId = orderId;
		this.totalAmt = totalAmt;
		this.timeStart = timeStart;
		this.timeExpire = timeExpire;
		this.paySta = paySta;
		this.rev = rev;
		this.returnCode = returnCode;
		this.returnMsg = returnMsg;
		this.resultCode = resultCode;
		this.errCode = errCode;
		this.errCodeDes = errCodeDes;
		this.tradeType = tradeType;
		this.prepayId = prepayId;
		this.codeUrl = codeUrl;
		this.bankType = bankType;
		this.transactionId = transactionId;
		this.payTimeEnd = payTimeEnd;
		this.sendChannle = sendChannle;
		this.orderDesc = orderDesc;
	}

	@Id

	@Column(name = "pay_seq", unique = true, nullable = false, length = 32)
	public String getPaySeq() {
		return this.paySeq;
	}

	public void setPaySeq(String paySeq) {
		this.paySeq = paySeq;
	}

	@Column(name = "inst_dt", length = 14)
	public String getInstDt() {
		return this.instDt;
	}

	public void setInstDt(String instDt) {
		this.instDt = instDt;
	}

	@Column(name = "pay_channle", length = 2)
	public String getPayChannle() {
		return this.payChannle;
	}

	public void setPayChannle(String payChannle) {
		this.payChannle = payChannle;
	}

	@Column(name = "order_id", length = 32)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "total_amt", length = 12)
	public String getTotalAmt() {
		return this.totalAmt;
	}

	public void setTotalAmt(String totalAmt) {
		this.totalAmt = totalAmt;
	}

	@Column(name = "time_start", length = 14)
	public String getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(String timeStart) {
		this.timeStart = timeStart;
	}

	@Column(name = "time_expire", length = 14)
	public String getTimeExpire() {
		return this.timeExpire;
	}

	public void setTimeExpire(String timeExpire) {
		this.timeExpire = timeExpire;
	}

	@Column(name = "pay_sta", length = 2)
	public String getPaySta() {
		return this.paySta;
	}

	public void setPaySta(String paySta) {
		this.paySta = paySta;
	}

	@Column(name = "rev", length = 50)
	public String getRev() {
		return this.rev;
	}

	public void setRev(String rev) {
		this.rev = rev;
	}

	@Column(name = "return_code", length = 16)
	public String getReturnCode() {
		return this.returnCode;
	}

	public void setReturnCode(String returnCode) {
		this.returnCode = returnCode;
	}

	@Column(name = "return_msg", length = 128)
	public String getReturnMsg() {
		return this.returnMsg;
	}

	public void setReturnMsg(String returnMsg) {
		this.returnMsg = returnMsg;
	}

	@Column(name = "result_code", length = 16)
	public String getResultCode() {
		return this.resultCode;
	}

	public void setResultCode(String resultCode) {
		this.resultCode = resultCode;
	}

	@Column(name = "err_code", length = 32)
	public String getErrCode() {
		return this.errCode;
	}

	public void setErrCode(String errCode) {
		this.errCode = errCode;
	}

	@Column(name = "err_code_des", length = 128)
	public String getErrCodeDes() {
		return this.errCodeDes;
	}

	public void setErrCodeDes(String errCodeDes) {
		this.errCodeDes = errCodeDes;
	}

	@Column(name = "trade_type", length = 16)
	public String getTradeType() {
		return this.tradeType;
	}

	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}

	@Column(name = "prepay_id", length = 64)
	public String getPrepayId() {
		return this.prepayId;
	}

	public void setPrepayId(String prepayId) {
		this.prepayId = prepayId;
	}

	@Column(name = "code_url", length = 64)
	public String getCodeUrl() {
		return this.codeUrl;
	}

	public void setCodeUrl(String codeUrl) {
		this.codeUrl = codeUrl;
	}

	@Column(name = "bank_type", length = 16)
	public String getBankType() {
		return this.bankType;
	}

	public void setBankType(String bankType) {
		this.bankType = bankType;
	}

	@Column(name = "transaction_id", length = 32)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "pay_time_end", length = 14)
	public String getPayTimeEnd() {
		return this.payTimeEnd;
	}

	public void setPayTimeEnd(String payTimeEnd) {
		this.payTimeEnd = payTimeEnd;
	}

	@Column(name = "send_channle", length = 1)
	public String getSendChannle() {
		return this.sendChannle;
	}

	public void setSendChannle(String sendChannle) {
		this.sendChannle = sendChannle;
	}

	@Column(name = "order_desc", length = 100)
	public String getOrderDesc() {
		return this.orderDesc;
	}

	public void setOrderDesc(String orderDesc) {
		this.orderDesc = orderDesc;
	}

}
