package com.app.bean;
// Generated 2016-10-22 17:15:41 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblResourcesInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_resources_info", catalog = "shopdata")
public class TblResourcesInfo implements java.io.Serializable {

	private String resid;
	private String keyid;
	private String type;
	private String resnm;
	private String url;
	private String status;
	private String newFileNm;
	private String instDt;
	private String modiDt;

	public TblResourcesInfo() {
	}

	public TblResourcesInfo(String resid) {
		this.resid = resid;
	}

	public TblResourcesInfo(String resid, String keyid, String type, String resnm, String url, String status,
			String newFileNm, String instDt, String modiDt) {
		this.resid = resid;
		this.keyid = keyid;
		this.type = type;
		this.resnm = resnm;
		this.url = url;
		this.status = status;
		this.newFileNm = newFileNm;
		this.instDt = instDt;
		this.modiDt = modiDt;
	}

	@Id

	@Column(name = "resid", unique = true, nullable = false, length = 32)
	public String getResid() {
		return this.resid;
	}

	public void setResid(String resid) {
		this.resid = resid;
	}

	@Column(name = "keyid", length = 32)
	public String getKeyid() {
		return this.keyid;
	}

	public void setKeyid(String keyid) {
		this.keyid = keyid;
	}

	@Column(name = "type", length = 2)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "resnm", length = 100)
	public String getResnm() {
		return this.resnm;
	}

	public void setResnm(String resnm) {
		this.resnm = resnm;
	}

	@Column(name = "url", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "newFileNm", length = 100)
	public String getNewFileNm() {
		return this.newFileNm;
	}

	public void setNewFileNm(String newFileNm) {
		this.newFileNm = newFileNm;
	}

	@Column(name = "inst_dt", length = 14)
	public String getInstDt() {
		return this.instDt;
	}

	public void setInstDt(String instDt) {
		this.instDt = instDt;
	}

	@Column(name = "modi_dt", length = 14)
	public String getModiDt() {
		return this.modiDt;
	}

	public void setModiDt(String modiDt) {
		this.modiDt = modiDt;
	}

}
