package com.app.bean;

// Generated 2016-7-4 23:14:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TblShopBannerInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_shop_banner_info", catalog = "shopdata")
public class TblShopBannerInfo implements java.io.Serializable {

	private String bid;
	private String shopId;
	private String type;
	private String title;
	private String resid;
	private String url;
	private Integer status;
	private Date instDt;
	private String instOper;
	private Date updtDt;
	private String updtOper;
	private String rev;

	public TblShopBannerInfo() {
	}

	public TblShopBannerInfo(String bid) {
		this.bid = bid;
	}

	public TblShopBannerInfo(String bid, String shopId, String type,
			String title, String resid, String url, Integer status,
			Date instDt, String instOper, Date updtDt, String updtOper,
			String rev) {
		this.bid = bid;
		this.shopId = shopId;
		this.type = type;
		this.title = title;
		this.resid = resid;
		this.url = url;
		this.status = status;
		this.instDt = instDt;
		this.instOper = instOper;
		this.updtDt = updtDt;
		this.updtOper = updtOper;
		this.rev = rev;
	}

	@Id
	@Column(name = "bid", unique = true, nullable = false, length = 32)
	public String getBid() {
		return this.bid;
	}

	public void setBid(String bid) {
		this.bid = bid;
	}

	@Column(name = "shop_id", length = 32)
	public String getShopId() {
		return this.shopId;
	}

	public void setShopId(String shopId) {
		this.shopId = shopId;
	}

	@Column(name = "type", length = 4)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "title", length = 60)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "resid", length = 32)
	public String getResid() {
		return this.resid;
	}

	public void setResid(String resid) {
		this.resid = resid;
	}

	@Column(name = "url", length = 500)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inst_dt", length = 19)
	public Date getInstDt() {
		return this.instDt;
	}

	public void setInstDt(Date instDt) {
		this.instDt = instDt;
	}

	@Column(name = "inst_oper", length = 20)
	public String getInstOper() {
		return this.instOper;
	}

	public void setInstOper(String instOper) {
		this.instOper = instOper;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updt_dt", length = 19)
	public Date getUpdtDt() {
		return this.updtDt;
	}

	public void setUpdtDt(Date updtDt) {
		this.updtDt = updtDt;
	}

	@Column(name = "updt_oper", length = 20)
	public String getUpdtOper() {
		return this.updtOper;
	}

	public void setUpdtOper(String updtOper) {
		this.updtOper = updtOper;
	}

	@Column(name = "rev", length = 100)
	public String getRev() {
		return this.rev;
	}

	public void setRev(String rev) {
		this.rev = rev;
	}

}
