package com.app.bean;

// Generated 2016-7-3 11:51:27 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblShopInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_shop_info", catalog = "shopdata")
public class TblShopInfo implements java.io.Serializable {

	private String shopId;
	private String shopNm;
	private String logo;
	private String type;
	private String level;
	private String sales;
	private String content;
	private String address;
	private String status;
	private String regDt;
	private String modiDt;
	private String cancelDt;
	private String totalscore;
	private String shopscore;
	private String serverscore;
	private String expresscore;
	private String shopsign;
	private String server;
	private String shopTel;

	public TblShopInfo() {
	}

	public TblShopInfo(String shopId) {
		this.shopId = shopId;
	}

	public TblShopInfo(String shopId, String shopNm, String logo, String type,
			String level, String sales, String content, String address,
			String status, String regDt, String modiDt, String cancelDt,
			String totalscore, String shopscore, String serverscore,
			String expresscore, String shopsign, String server, String shopTel) {
		this.shopId = shopId;
		this.shopNm = shopNm;
		this.logo = logo;
		this.type = type;
		this.level = level;
		this.sales = sales;
		this.content = content;
		this.address = address;
		this.status = status;
		this.regDt = regDt;
		this.modiDt = modiDt;
		this.cancelDt = cancelDt;
		this.totalscore = totalscore;
		this.shopscore = shopscore;
		this.serverscore = serverscore;
		this.expresscore = expresscore;
		this.shopsign = shopsign;
		this.server = server;
		this.shopTel = shopTel;
	}

	@Id
	@Column(name = "shop_id", unique = true, nullable = false, length = 32)
	public String getShopId() {
		return this.shopId;
	}

	public void setShopId(String shopId) {
		this.shopId = shopId;
	}

	@Column(name = "shop_nm", length = 100)
	public String getShopNm() {
		return this.shopNm;
	}

	public void setShopNm(String shopNm) {
		this.shopNm = shopNm;
	}

	@Column(name = "logo", length = 32)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "type", length = 1)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "level", length = 1)
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	@Column(name = "sales", length = 100)
	public String getSales() {
		return this.sales;
	}

	public void setSales(String sales) {
		this.sales = sales;
	}

	@Column(name = "content", length = 500)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "reg_dt", length = 14)
	public String getRegDt() {
		return this.regDt;
	}

	public void setRegDt(String regDt) {
		this.regDt = regDt;
	}

	@Column(name = "modi_dt", length = 14)
	public String getModiDt() {
		return this.modiDt;
	}

	public void setModiDt(String modiDt) {
		this.modiDt = modiDt;
	}

	@Column(name = "cancel_dt", length = 14)
	public String getCancelDt() {
		return this.cancelDt;
	}

	public void setCancelDt(String cancelDt) {
		this.cancelDt = cancelDt;
	}

	@Column(name = "totalscore", length = 4)
	public String getTotalscore() {
		return this.totalscore;
	}

	public void setTotalscore(String totalscore) {
		this.totalscore = totalscore;
	}

	@Column(name = "shopscore", length = 4)
	public String getShopscore() {
		return this.shopscore;
	}

	public void setShopscore(String shopscore) {
		this.shopscore = shopscore;
	}

	@Column(name = "serverscore", length = 4)
	public String getServerscore() {
		return this.serverscore;
	}

	public void setServerscore(String serverscore) {
		this.serverscore = serverscore;
	}

	@Column(name = "expresscore", length = 4)
	public String getExpresscore() {
		return this.expresscore;
	}

	public void setExpresscore(String expresscore) {
		this.expresscore = expresscore;
	}

	@Column(name = "shopsign", length = 32)
	public String getShopsign() {
		return this.shopsign;
	}

	public void setShopsign(String shopsign) {
		this.shopsign = shopsign;
	}

	@Column(name = "server", length = 10)
	public String getServer() {
		return this.server;
	}

	public void setServer(String server) {
		this.server = server;
	}

	@Column(name = "shop_tel", length = 20)
	public String getShopTel() {
		return this.shopTel;
	}

	public void setShopTel(String shopTel) {
		this.shopTel = shopTel;
	}

}
