package com.app.bean;
// Generated 2017-5-12 11:28:19 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblSmsInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_sms_info", catalog = "shopdata")
public class TblSmsInfo implements java.io.Serializable {

	private String smsId;
	private String telphone;
	private String smsType;
	private String smsCode;
	private String sndTm;
	private Integer errNum;
	private Integer expires;

	public TblSmsInfo() {
	}

	public TblSmsInfo(String smsId) {
		this.smsId = smsId;
	}

	public TblSmsInfo(String smsId, String telphone, String smsType, String smsCode, String sndTm, Integer errNum,
			Integer expires) {
		this.smsId = smsId;
		this.telphone = telphone;
		this.smsType = smsType;
		this.smsCode = smsCode;
		this.sndTm = sndTm;
		this.errNum = errNum;
		this.expires = expires;
	}

	@Id

	@Column(name = "sms_id", unique = true, nullable = false, length = 22)
	public String getSmsId() {
		return this.smsId;
	}

	public void setSmsId(String smsId) {
		this.smsId = smsId;
	}

	@Column(name = "telphone", length = 11)
	public String getTelphone() {
		return this.telphone;
	}

	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}

	@Column(name = "sms_type", length = 2)
	public String getSmsType() {
		return this.smsType;
	}

	public void setSmsType(String smsType) {
		this.smsType = smsType;
	}

	@Column(name = "sms_code", length = 6)
	public String getSmsCode() {
		return this.smsCode;
	}

	public void setSmsCode(String smsCode) {
		this.smsCode = smsCode;
	}

	@Column(name = "snd_tm", length = 14)
	public String getSndTm() {
		return this.sndTm;
	}

	public void setSndTm(String sndTm) {
		this.sndTm = sndTm;
	}

	@Column(name = "err_num")
	public Integer getErrNum() {
		return this.errNum;
	}

	public void setErrNum(Integer errNum) {
		this.errNum = errNum;
	}

	@Column(name = "expires")
	public Integer getExpires() {
		return this.expires;
	}

	public void setExpires(Integer expires) {
		this.expires = expires;
	}

}
