package com.app.bean;

// Generated 2016-6-3 23:47:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblTgInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_tg_info", catalog = "shopdata")
public class TblTgInfo implements java.io.Serializable {

	private Long tid;
	private String classify;
	private String goodsId;
	private Date startdt;
	private Date enddt;
	private Character flag;

	public TblTgInfo() {
	}

	public TblTgInfo(String classify, String goodsId, Date startdt, Date enddt,
			Character flag) {
		this.classify = classify;
		this.goodsId = goodsId;
		this.startdt = startdt;
		this.enddt = enddt;
		this.flag = flag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tid", unique = true, nullable = false)
	public Long getTid() {
		return this.tid;
	}

	public void setTid(Long tid) {
		this.tid = tid;
	}

	@Column(name = "classify", length = 8)
	public String getClassify() {
		return this.classify;
	}

	public void setClassify(String classify) {
		this.classify = classify;
	}

	@Column(name = "goods_id", length = 20)
	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startdt", length = 19)
	public Date getStartdt() {
		return this.startdt;
	}

	public void setStartdt(Date startdt) {
		this.startdt = startdt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "enddt", length = 19)
	public Date getEnddt() {
		return this.enddt;
	}

	public void setEnddt(Date enddt) {
		this.enddt = enddt;
	}

	@Column(name = "flag", length = 1)
	public Character getFlag() {
		return this.flag;
	}

	public void setFlag(Character flag) {
		this.flag = flag;
	}

}
