package com.app.bean;

// Generated 2016-6-4 23:19:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblYfInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_yf_info", catalog = "shopdata")
public class TblYfInfo implements java.io.Serializable {

	private String yfId;
	private String shopId;
	private String yfNm;
	private String amount;
	private String rev;

	public TblYfInfo() {
	}

	public TblYfInfo(String yfId) {
		this.yfId = yfId;
	}

	public TblYfInfo(String yfId, String shopId, String yfNm, String amount,
			String rev) {
		this.yfId = yfId;
		this.shopId = shopId;
		this.yfNm = yfNm;
		this.amount = amount;
		this.rev = rev;
	}

	@Id
	@Column(name = "yf_id", unique = true, nullable = false, length = 32)
	public String getYfId() {
		return this.yfId;
	}

	public void setYfId(String yfId) {
		this.yfId = yfId;
	}

	@Column(name = "shop_id", length = 32)
	public String getShopId() {
		return this.shopId;
	}

	public void setShopId(String shopId) {
		this.shopId = shopId;
	}

	@Column(name = "yf_nm", length = 30)
	public String getYfNm() {
		return this.yfNm;
	}

	public void setYfNm(String yfNm) {
		this.yfNm = yfNm;
	}

	@Column(name = "amount", length = 12)
	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	@Column(name = "rev", length = 30)
	public String getRev() {
		return this.rev;
	}

	public void setRev(String rev) {
		this.rev = rev;
	}

}
